### ISSUE TITLE
Supporting mk files

### ISSUE THREAD

**Issue by uuf6429** [textmate/make.tmbundle#12]
I tried using this tm bundle within PhpStorm, (I've successfully used others in the past), however it doesn't seem to work for [`*.mk` files](https://www.gnu.org/software/make/manual/html_node/Include.html).

From my limited knowledge of tmbundles, this is because the file extension is missing [here](https://github.com/textmate/make.tmbundle/blob/master/Syntaxes/Makefile.plist#L6).

That said, I tried changing the file locally and it still wouldn't work... I'm sure I'm missing something - I don't know much about how tmbundles work..

**Comment by sorbits** [comment]
Please use PhpStorm’s support channel for your issue, as we do not provide support for third party software that make use TextMate’s bundles.

**Comment by uuf6429** [comment]
I think I was pretty clear that the problem does not seem to be PhpStorm-specific:
> From my limited knowledge of tmbundles, this is because the file extension is missing here.

Let me put it into other words, if you open a .mk file in textmate with this tmbundle, does it get highlighted correctly?
