### ISSUE TITLE
Make doesn't use a login shell

### ISSUE THREAD

**Issue by shauninman** [textmate/make.tmbundle#19]
As a result, running a makefile that works in Terminal.app from TextMate.app can fail or produce unexpected results.

**Comment by sorbits** [comment]
I think the proper way to workaround such issue would be either to set `SHELL` or `PATH` in your `Makefile` (if it does not work with `/bin/sh`, or alternatively, create a wrapper script that sets up whatever you set up in your login shell, call `make`, and then set TextMate to use this wrapper via `TM_MAKE`.

It is generally not a good idea to run the user’s login shell for batch scripts.
