### ISSUE TITLE
sugestion: phony targets shoud be colored with different color

### ISSUE THREAD

**Issue by yukulele** [textmate/make.tmbundle#21]
in this example, "build" in line 1 should not have the same color as "style.css" because it's a phony target

```makefile
build:
    npm run build

style.css: style.scss
    sass style.scss

.PHONY: build
```

This should help to check if a target is not in .PHONY

**Comment by sorbits** [comment]
The current grammar system is not capable of supporting this.

A dedicated parser for `make` files would be required, but there is currently no API inplace for this.

Closing issue due to lack of feasibility, but not a bad idea :)
