### ISSUE TITLE
Makefile syntax highlighting bug

### ISSUE THREAD

**Issue by philtay** [textmate/make.tmbundle#9]
GitHub uses this bundle for Makefile syntax highlighting. Please have a look at this gist:

https://gist.github.com/philtay/5a647f5a573d1052e7f7

The same problem affects TextMate.

Repro:

```Makefile
define foobar
$(and $(filter-out undefined,$(origin 1)),$(1))
endef

define test
command
endef
```

Ref: https://github.com/github/linguist/issues/2710

**Comment by infininight** [comment]
Corrected in 1a1827da81e20fdce56e2658451340c070ca44b7, this is deployed in TextMate but will not be live on Github until the next linguist periodic update in 1-4 weeks.
